<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Pradeep_Machine" failures="2" tests="11" name="Test" time="490.202" errors="0" timestamp="2024-01-26T00:18:22 IST">
  <testcase classname="testCases.TC_002_LoginTest" name="verify_login" time="51.331">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC_002_LoginTest.verify_login(TC_002_LoginTest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_login -->
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="41.12">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_LoginDDT.verify_loginDDT(TC_003_LoginDDT.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="31.661"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="42.02"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="40.873"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="41.337"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="41.039"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="40.922"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="41.027"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="41.022"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="40.538"/>
</testsuite> <!-- Test -->
